evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,l), true).
evidence(chol(y,l), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,l), true).
evidence(chol(n,l), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,n), true).
evidence(cp(n,n), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,l), true).
evidence(chol(n,l), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,l), true).
evidence(chol(y,l), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,n), true).
evidence(cp(n,n), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,h), true).
evidence(chol(y,h), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,n), true).
evidence(cp(n,n), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,l), true).
evidence(thalach(n,l), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,n), true).
evidence(cp(n,n), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,m), true).
evidence(cp(n,m), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,n), true).
evidence(cp(n,n), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,l), true).
evidence(trestbps(y,l), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,f), true).
evidence(sex(n,f), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,h), true).
evidence(trestbps(n,h), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,m), true).
evidence(cp(y,m), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,h), true).
evidence(age(n,h), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,l), true).
evidence(cp(n,l), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,m), true).
evidence(thalach(y,m), false).
-----
evidence(age(n,l), true).
evidence(age(y,l), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,m), true).
evidence(age(n,m), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,m), true).
evidence(trestbps(n,m), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,m), true).
evidence(thalach(n,m), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,h), true).
evidence(cp(y,h), false).
evidence(trestbps(n,m), true).
evidence(trestbps(y,m), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(y,l), true).
evidence(age(n,l), false).
evidence(sex(y,m), true).
evidence(sex(n,m), false).
evidence(cp(y,h), true).
evidence(cp(n,h), false).
evidence(trestbps(y,l), true).
evidence(trestbps(n,l), false).
evidence(chol(y,m), true).
evidence(chol(n,m), false).
evidence(thalach(y,h), true).
evidence(thalach(n,h), false).
-----
evidence(age(n,h), true).
evidence(age(y,h), false).
evidence(sex(n,f), true).
evidence(sex(y,f), false).
evidence(cp(n,l), true).
evidence(cp(y,l), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
evidence(age(n,m), true).
evidence(age(y,m), false).
evidence(sex(n,m), true).
evidence(sex(y,m), false).
evidence(cp(n,n), true).
evidence(cp(y,n), false).
evidence(trestbps(n,h), true).
evidence(trestbps(y,h), false).
evidence(chol(n,m), true).
evidence(chol(y,m), false).
evidence(thalach(n,h), true).
evidence(thalach(y,h), false).
-----
